name: build-binary

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -o fp-devops main.go
        working-directory: ./app

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fp-devops-binary
          path: ./app/fp-devops
      
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker Image
        run: docker compose up -d --build
        working-directory: ./app


      - name: Upload Artifact (khusus untuk push ke main)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: go-app-binary
          path: ./app/main # atau path ke binary hasil build jika beda
